#!/bin/bash
set -e

cat <<EOF
Starting TOPS-10 on PDP-10

  See readme for details

  Ctrl-E, quit to exit.

EOF

SCRIPTFULL="$(readlink -f "$0")"
SCRIPTDIR="$(dirname "${SCRIPTFULL}")"
cd "${SCRIPTDIR}/files"
exec pdp10 tops10.cfg "$@"
