#!/bin/bash

if [ -z "$1" ]; then
    echo "Usage: $0 list | $0 game ..."
    exit 5
fi

listgames () {
    for ITEM in `ls /usr/games`; do
        whatis "$ITEM"
    done
}

if [ "$1" = "list" ]; then
    # We only want things in man section 6 (games)
    listgames | grep 6
    exit 0
fi

GAME="$1"
shift
exec "/usr/games/${GAME}" "$@"
