#!/bin/bash
set -e

cat <<EOF
Starting UNIX V7 on PDP-11

  There will be no prompt; just type "boot"  Then at the ":" prompt, type
  "hp(0,0)munix".  At the "#" prompt, type Ctrl-D, then login
  as root, password root.  A user login is available as wsenn, password wsenn5.

  For additional logins, "telnet localhost 4000".

  Ctrl-E, quit to exit.

EOF

SCRIPTFULL="$(readlink -f "$0")"
SCRIPTDIR="$(dirname "${SCRIPTFULL}")"
cd "${SCRIPTDIR}/files"
exec pdp11 unixv7.simh "$@"
