#!/bin/bash

set -e

if [ "`id -u`" = "0" ]; then
    cd ~pi
    exec sudo -H -i -u pi "$0" "$@"
fi

BASEDIR="/opt/vint"

if [ -z "$1" ]; then
    echo "Usage: $0 program [...]"
    echo ""
    echo "Valid programs are:"
    echo ""
    cd "${BASEDIR}/systems"
    ls
    exit 5
fi

SYSTEM="$1"
shift
exec "${BASEDIR}/systems/${SYSTEM}/run" "$@"
