#!/bin/bash
set -e

cat <<EOF
Starting UNIX V6 on PDP-11

  Type "unix" at "@" prompt, then type "root" at login prompt.

  For additional logins, "telnet localhost 4000".

  Ctrl-E, quit to exit.

EOF

SCRIPTFULL="$(readlink -f "$0")"
SCRIPTDIR="$(dirname "${SCRIPTFULL}")"
cd "${SCRIPTDIR}/files"
exec pdp11 unixv6.simh "$@"
